# Generated by Django 5.0 on 2023-12-27 19:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoContagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contagem', models.DateField(default=django.utils.timezone.now)),
                ('quantidade_contagem', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_contagem', to='produtos.produto')),
            ],
            options={
                'ordering': ['-data_contagem'],
                'get_latest_by': 'data_contagem',
            },
        ),
    ]
