# Generated by Django 5.0 on 2023-12-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_historicocontagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nivel_minimo',
            field=models.IntegerField(default=15),
        ),
    ]
