# Generated by Django 5.0 on 2024-01-25 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0003_local_restaurante_historicolog_data_devolucao_and_more'),
        ('produtos', '0003_produto_nivel_minimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='historicocontagem',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.local'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='EstoqueProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.local')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='produtos.produto')),
            ],
        ),
    ]
