# Generated by Django 5.0.1 on 2024-02-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_remove_produto_quantidade_historicocontagem_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='apelido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
