# Generated by Django 5.0.1 on 2024-02-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_estoqueproduto_apelido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoqueproduto',
            name='apelido',
        ),
    ]
