# Generated by Django 5.0.1 on 2024-03-13 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_initial'),
        ('gestao_estoque', '0019_transacoe_motivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_acessar', models.BooleanField(default=False)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_acesso', to='gestao_estoque.restaurante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_restaurante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'restaurante')},
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
