# Generated by Django 5.0 on 2024-01-25 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao_estoque', '0003_local_restaurante_historicolog_data_devolucao_and_more'),
        ('produtos', '0004_remove_produto_quantidade_historicocontagem_local_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField(choices=[('EM', 'Empréstimo'), ('DE', 'Devolução')], max_length=2)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.restaurante')),
            ],
        ),
    ]
