# Generated by Django 5.0.1 on 2024-02-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transacao',
        ),
    ]
