# Generated by Django 5.0 on 2023-12-30 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0001_initial'),
        ('produtos', '0003_produto_nivel_minimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricoTransacao',
            new_name='HistoricoLog',
        ),
    ]
