# Generated by Django 5.0 on 2024-01-25 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0002_rename_historicotransacao_historicolog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='historicolog',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicolog',
            name='status',
            field=models.CharField(choices=[('EM', 'Emprestado'), ('DI', 'Disponível'), ('ND', 'Não Devolvido')], default='DI', max_length=2),
        ),
        migrations.AlterField(
            model_name='historicolog',
            name='tipo',
            field=models.CharField(choices=[('AD', 'Adição'), ('RE', 'Remoção'), ('EM', 'Empréstimo'), ('DE', 'Devolução')], max_length=2),
        ),
        migrations.AddField(
            model_name='historicolog',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.local'),
        ),
        migrations.AddField(
            model_name='historicolog',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_estoque.restaurante'),
        ),
    ]
