# Generated by Django 5.0.1 on 2024-01-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0003_local_restaurante_historicolog_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_estoque.restaurante'),
        ),
    ]
