# Generated by Django 5.0.1 on 2024-02-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0006_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='estado_solicitacao',
            field=models.CharField(choices=[('PE', 'Pendente'), ('AP', 'Aprovado'), ('RE', 'Rejeitado')], default='PE', max_length=2),
        ),
    ]
