# Generated by Django 5.0 on 2024-02-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0007_transacao_estado_solicitacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'permissions': (('can_approve_transaction', 'Can approve transaction'), ('can_reject_transaction', 'Can reject transaction'))},
        ),
    ]
