# Generated by Django 5.0 on 2024-02-07 12:49

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0011_alter_transacao_responsavel_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='responsavel_por',
            field=models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
