# Generated by Django 5.0.1 on 2024-02-15 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0012_alter_transacao_responsavel_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicolog',
            name='status',
            field=models.CharField(choices=[('EM', 'Emprestado'), ('DI', 'Disponível'), ('ND', 'Não Devolvido'), ('RJ', 'Rejeitado')], default='DI', max_length=2),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='responsavel_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
