# Generated by Django 5.0.1 on 2024-02-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0013_alter_historicolog_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicolog',
            name='tipo',
            field=models.CharField(choices=[('AD', 'Adição'), ('RE', 'Remoção'), ('RJ', 'Rejeição'), ('EM', 'Empréstimo'), ('DE', 'Devolução')], max_length=2),
        ),
    ]
