# Generated by Django 5.0.1 on 2024-02-16 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0014_alter_historicolog_tipo'),
        ('produtos', '0004_remove_produto_quantidade_historicocontagem_local_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transacao',
            new_name='Transacoe',
        ),
    ]
