# Generated by Django 5.0.1 on 2024-02-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0016_alter_historicolog_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicolog',
            name='tipo',
            field=models.CharField(choices=[('AD', 'Adição'), ('RE', 'Remoção'), ('RJ', 'Rejeição'), ('EM', 'Empréstimo'), ('DE', 'Devolução'), ('AT', 'Atualização')], max_length=10),
        ),
    ]
