# Generated by Django 5.0.1 on 2024-02-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0017_alter_historicolog_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicolog',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
