# Generated by Django 5.0.3 on 2024-03-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0018_historicolog_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacoe',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
