# Generated by Django 5.0.1 on 2024-04-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0021_alter_transacoe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacoe',
            options={'permissions': (('can_approve_transaction', 'Pode aprovar transação'), ('can_reject_transaction', 'Pode rejeitar transação'), ('can_update', 'Pode atualizar'), ('can_register_loss', 'Pode registrar perda'), ('can_transact', 'Pode realizar transação'), ('can_loan', 'Pode realizar empréstimo'), ('can_return', 'Pode realizar devolução'))},
        ),
        migrations.AlterField(
            model_name='historicolog',
            name='status',
            field=models.CharField(choices=[('EM', 'Emprestado'), ('TR', 'Transacionado'), ('DI', 'Disponível'), ('ND', 'Não Devolvido'), ('RJ', 'Rejeitado')], default='DI', max_length=2),
        ),
        migrations.AlterField(
            model_name='historicolog',
            name='tipo',
            field=models.CharField(choices=[('AD', 'Adição'), ('RE', 'Remoção'), ('RJ', 'Rejeição'), ('EM', 'Empréstimo'), ('DE', 'Devolução'), ('AT', 'Atualização'), ('TR', 'Transação')], max_length=10),
        ),
    ]
